{{- range $i, $user := .Values.users }}
{{- if and $user.accessKey $user.secretKey (not $user.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minio-aistor.fullname" $ }}-user-{{ $user.accessKey | lower | replace "_" "-" | replace "." "-" }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "minio-aistor.labels" $ | nindent 4 }}
    app.kubernetes.io/component: provisioning
  {{- with $.Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  access-key: {{ $user.accessKey | b64enc | quote }}
  secret-key: {{ $user.secretKey | b64enc | quote }}
{{- end }}
{{- end }}
