{{- if not .Values.minio.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minio-aistor.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "minio-aistor.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.minio.auth.rootUser }}
  root-user: {{ .Values.minio.auth.rootUser | b64enc | quote }}
  {{- else }}
  root-user: {{ "admin" | b64enc | quote }}
  {{- end }}
  {{- if .Values.minio.auth.rootPassword }}
  root-password: {{ .Values.minio.auth.rootPassword | b64enc | quote }}
  {{- else }}
  root-password: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
{{- end }}
---
{{- if and .Values.minio.license.enabled (not .Values.minio.license.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minio-aistor.fullname" . }}-license
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "minio-aistor.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  minio.license: {{ .Values.minio.license.content | b64enc | quote }}
{{- end }}
